### ISSUE TITLE
HamburgerMenu

### ISSUE THREAD

**Issue by Terppe** [Terppe/ATIS#3]
@LMStudent In mein MainWindow soll ein MamburgerMenu eingebaut werden.

The HamburgerMenu is no longer available in the Windows Community Toolkit. Please use the NavigationView. Read the Moving to NavigationView section for more info. 

The Windows 10 Fall Creators Update SDK enthält nun NavigationView. Da komme ich nicht klar.

**Comment by LMStudent** [comment]
@Terppe Ist diese Frage noch aktuell? Ich bekomme für diesen Account leider keine Benachrichtigungen. Besser geht es, wenn du @suchja anschreibst.

**Comment by Terppe** [comment]
@suchja ich installed in my MainWindow the new NavigtionView. The problem is that the connected UserControl (HomeView) does not expand, if I change NavigationView to LeftMinimal. Cannot find a result
